import DummyImf from "@/images/projectDummy.png";

export const PROJECTS_DATA = [
  {
    id: 1,
    title: "Luxury Bedroom",
    category: "RESIDENTIAL INTERIOR",
    location: "AHMEDABAD",
    slug: "luxury-bedroom",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    client: "Vijay Trivedi",
    value: "70,000 INR",
    area: "200 Sq. Ft.",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 2,
    title: "Modern Bedroom",
    category: "RESIDENTIAL INTERIOR",
    location: "MEHSANA",
    slug: "modern-bedroom",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    client: "Amit Shah",
    value: "85,000 INR",
    area: "240 Sq. Ft.",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },
  {
    id: 3,
    title: "3D Bedroom Visualization",
    category: "3D VISUALIZATION",
    location: "SURAT",
    slug: "3d-bedroom-visualization",
    description:
      "High-quality 3D visualization showcasing lighting, materials, and layout.",
    client: "Internal Concept",
    value: "—",
    area: "—",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    // gallery: Array(6).fill("/images/project/projectDummy.png"),
    image: DummyImf,
  },
  {
    id: 4,
    title: "Commercial Office Space",
    category: "COMMERCIAL INTERIOR",
    location: "MUMBAI",
    slug: "commercial-office-space",
    description:
      "Functional and modern office interior designed for productivity.",
    client: "Zen Corp",
    value: "2,50,000 INR",
    area: "850 Sq. Ft.",
     gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },
   {
    id: 5,
    title: "Architectural Living Room",
    category: "ARCHITECTURE",
    location: "PUNE",
    slug: "architectural-living-room",
    description:
      "Architectural interior with strong spatial planning and aesthetics.",
    client: "Private Residence",
    value: "1,20,000 INR",
    area: "420 Sq. Ft.",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 6,
    title: "Premium Villa Interior",
    category: "RESIDENTIAL INTERIOR",
    location: "AHMEDABAD",
    slug: "premium-villa-interior",
    description:
      "High-end villa interior with premium finishes and detailing.",
    client: "Rohit Mehta",
    value: "4,80,000 INR",
    area: "1800 Sq. Ft.",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 7,
    title: "3D Kitchen Render",
    category: "3D VISUALIZATION",
    location: "DELHI",
    slug: "3d-kitchen-render",
    description:
      "Realistic kitchen render created for design visualization.",
    client: "Design Proposal",
    value: "—",
    area: "—",
     gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 8,
    title: "Retail Store Interior",
    category: "COMMERCIAL INTERIOR",
    location: "BENGALURU",
    slug: "retail-store-interior",
    description:
      "Retail interior focused on customer experience and brand identity.",
    client: "Urban Wear",
    value: "3,10,000 INR",
    area: "950 Sq. Ft.",
     gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 9,
    title: "Minimal Architecture Concept",
    category: "ARCHITECTURE",
    location: "JAIPUR",
    slug: "minimal-architecture-concept",
    description:
      "Conceptual architectural interior with minimal design language.",
    client: "Concept Project",
    value: "—",
    area: "—",
    gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  {
    id: 10,
    title: "Luxury Living Room Interior",
    category: "RESIDENTIAL INTERIOR",
    location: "CHENNAI",
    slug: "luxury-living-room-interior",
    description:
      "Luxury living room interior with warm tones and layered lighting.",
    client: "Arjun Patel",
    value: "1,90,000 INR",
    area: "560 Sq. Ft.",
     gallery: [
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
      "/images/project/projectDummy.png",
    ],
    image: DummyImf,
  },

  

];
