import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const helveticaNeue = localFont({
  src: [
    {
      path: "../fonts/HelveticaNeueBlack.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/HelveticaNeueLight.otf",
      weight: "400",
      style: "light",
    },
  ],
  variable: "--font-helvetica-neue",
  display: "swap",
});

export const metadata = {
  title: "Unity Interiors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={helveticaNeue.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
